# Generated by Django 4.2.7 on 2023-12-16 00:12

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25, verbose_name="Название")),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads_model",
                        validators=[main.validators.validate_file_extension],
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
            },
        ),
    ]
